image: docker:stable-git

before_script:
  - docker info

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  tags:
    - docker
    - large
  script:
    - make all
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker tag compiler uubk/mt-compiler:${CI_COMMIT_SHA}
    - docker push uubk/mt-compiler:${CI_COMMIT_SHA}
    - docker tag compiler uubk/mt-compiler:latest
    - docker push uubk/mt-compiler:latest
