build:
  tags:
    - shell
  script:
    - make all
    - docker tag compiler registry.njsm.de/mt/compiler:latest
    - docker push registry.njsm.de/mt/compiler:latest
    - docker tag compiler registry.njsm.de/mt/compiler:${CI_COMMIT_SHA}
    - docker push registry.njsm.de/mt/compiler:${CI_COMMIT_SHA}
    - sudo chown -R $(id -u):$(id -g) .
