FROM debian:buster

RUN apt update && \
  apt upgrade -y && \
  apt install -y build-essential \
                 ninja-build \
                 git \
                 cmake \
                 python \
		 binutils-dev
CMD ["/bin/bash", "-c", "cd /opt/toolchain && ./mktoolchain.sh && tar -cvf tools.tar -C target ."]
